# Generated by Django 6.0.7 on 2026-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('finale', 'Finale'), ('mid', 'Mid'), ('practice', 'Practice')], default='practice', max_length=10),
        ),
    ]
