# Generated by Django 6.0.7 on 2026-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('finale', 'Finale'), ('mid', 'Mid'), ('practice', 'Practice'), ('saq', 'SAQ'), ('ospe', 'OSPE')], default='practice', max_length=10),
        ),
    ]
