# Generated by Django 6.0.7 on 2026-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Image link'),
        ),
    ]
