# Generated by Django 6.0.7 on 2026-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examquestion_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('practice', 'Practice'), ('mid', 'Mid'), ('finale', 'Finale'), ('ospe', 'OSPE'), ('saq', 'SAQ')], default='practice', max_length=10),
        ),
    ]
