# Generated by Django 6.0.6 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examattempt_examanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='retry_times',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Total number of attempts allowed for each student.',
            ),
        ),
    ]
