# Generated by Django 6.0.7 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_retry_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
    ]
