# Generated by Django 6.0.7 on 2026-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_examanswer_text_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Make this exam available to every authenticated student.'),
        ),
    ]
