# Generated by Django 6.0.7 on 2026-09-10

from django.db import migrations, models


def assign_existing_exam_order(apps, schema_editor):
    Exam = apps.get_model('exams', 'Exam')
    module_ids = Exam.objects.order_by().values_list('module_id', flat=True).distinct()
    for module_id in module_ids:
        exams = Exam.objects.filter(module_id=module_id).order_by('name', 'pk')
        for order, exam in enumerate(exams, start=1):
            Exam.objects.filter(pk=exam.pk).update(order=order)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Display order within this module.'),
        ),
        migrations.RunPython(assign_existing_exam_order, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('year', 'module__order', 'order', 'pk')},
        ),
    ]
