# Generated by Django 6.0.6 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_exam_is_trial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('year', 'module__order', 'order', 'name')},
        ),
        migrations.AddField(
            model_name='exam',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
