# Generated by Django 6.0.6 on 2026-09-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_exam_options_exam_order'),
        ('modules', '0008_moduleexamsubject_moduleexamweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subjects are configured in the selected module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='modules.moduleexamsubject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='week',
            field=models.ForeignKey(blank=True, help_text='Weeks are configured in the selected module.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='modules.moduleexamweek'),
        ),
    ]
