# Generated by Django 6.0.7 on 2026-09-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_order'),
        ('exams', '0011_exam_subject_exam_week'),
    ]

    operations = [
    ]
