# Generated by Django 6.0.7 on 2026-09-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_merge_0010_exam_order_0011_exam_subject_exam_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('year', 'module__order', 'order', 'name')},
        ),
        migrations.AlterField(
            model_name='exam',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
