# Generated by Django 6.0.7 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentverification',
            name='activation_year',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')],
                help_text='Select the academic year this activation unlocks.',
                null=True,
            ),
        ),
    ]
