# Generated by Django 6.0.6 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0004_module_has_lessons_alter_module_has_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_subcategories', to='modules.module')),
            ],
            options={
                'verbose_name': 'Video subcategory',
                'verbose_name_plural': 'Video subcategories',
                'ordering': ('module__year', 'module__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(help_text='Paste a YouTube or embeddable video link.')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='modules.module')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.videosubcategory')),
            ],
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos', 'ordering': ('year', 'module__order', 'name')},
        ),
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watches', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='videos.video')),
            ],
            options={'verbose_name': 'Video watch', 'verbose_name_plural': 'Video watches'},
        ),
        migrations.AddConstraint(
            model_name='videosubcategory',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_video_subcategory_name_per_module'),
        ),
        migrations.AddConstraint(
            model_name='videowatch',
            constraint=models.UniqueConstraint(fields=('student', 'video'), name='unique_video_watch_per_student'),
        ),
    ]
