# Generated by Django 6.0.7 on 2026-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Make this video available to every authenticated student.'),
        ),
    ]
