# Generated by Django 6.0.7 on 2026-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_replace_year_with_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='has_exams',
            field=models.BooleanField(default=False, verbose_name='Exams section'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_files',
            field=models.BooleanField(default=False, verbose_name='Files section'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_osce',
            field=models.BooleanField(default=False, verbose_name='OSCE section'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_text',
            field=models.BooleanField(default=False, verbose_name='Text section'),
        ),
        migrations.AddField(
            model_name='module',
            name='has_videos',
            field=models.BooleanField(default=False, verbose_name='Videos section'),
        ),
    ]
