# Generated by Django 6.0.7 on 2026-07-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_module_has_exams_module_has_files_module_has_osce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='has_lessons',
            field=models.BooleanField(default=False, verbose_name='Lessons section'),
        ),
        migrations.AlterField(
            model_name='module',
            name='has_exams',
            field=models.BooleanField(default=True, verbose_name='Exams section'),
        ),
    ]
