# Generated by Django 6.0.6 on 2026-09-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_module_button_color_palette'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleExamSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subjects', to='modules.module')),
            ],
            options={
                'verbose_name': 'exam subject',
                'verbose_name_plural': 'Exam subjects',
                'ordering': ('order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('module', 'name'), name='unique_exam_subject_per_module')],
            },
        ),
        migrations.CreateModel(
            name='ModuleExamWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='For example: Week 1, Week 2, or Revision week.', max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_weeks', to='modules.module')),
            ],
            options={
                'verbose_name': 'exam week',
                'verbose_name_plural': 'Exam weeks',
                'ordering': ('order', 'name'),
                'constraints': [models.UniqueConstraint(fields=('module', 'name'), name='unique_exam_week_per_module')],
            },
        ),
    ]
