# Generated by Django 6.0.7 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0004_module_has_lessons_alter_module_has_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.CharField(help_text='For example: 2.4 MB', max_length=20)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('powerpoint', 'PowerPoint')], max_length=20)),
                ('file_link', models.URLField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_files', to='modules.module')),
            ],
            options={
                'verbose_name': 'Study file',
                'verbose_name_plural': 'Study files',
                'ordering': ('year', 'module__order', 'file_name'),
            },
        ),
    ]
