# Generated by Django 6.0.7 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_subcategories', to='modules.module')),
            ],
            options={
                'verbose_name': 'File subcategory',
                'verbose_name_plural': 'File subcategories',
                'ordering': ('module__year', 'module__order', 'order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='studyfile',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_files', to='files.filesubcategory'),
        ),
        migrations.AddConstraint(
            model_name='filesubcategory',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_file_subcategory_name_per_module'),
        ),
    ]
