# Generated by Django 6.0.7 on 2026-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filesubcategory_studyfile_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfile',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Make this file available to every authenticated student.'),
        ),
    ]
