# Generated by Django 6.0.6 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_all_features', models.BooleanField(default=False, help_text='Give every authenticated user access to all learning content.')),
                ('lock_all_features', models.BooleanField(default=True, help_text='Restrict unactivated users to trial content only.')),
            ],
            options={
                'verbose_name': 'website settings',
                'verbose_name_plural': 'website settings',
            },
        ),
    ]
