# Generated by Django 6.0.7 on 2026-08-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('notes', '0001_initial')]

    operations = [
        migrations.AlterField(model_name='note', name='color', field=models.CharField(default='#3b82f6', editable=False, max_length=7)),
        migrations.AlterField(model_name='note', name='module', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='modules.module')),
        migrations.AlterField(model_name='note', name='year', field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], null=True)),
    ]
