# Generated by Django 6.0.6 on 2026-08-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_weekly_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rank',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='rank',
            name='image_url',
            field=models.URLField(blank=True, help_text='Public URL of the rank icon image.'),
        ),
    ]
