# Generated by Django 6.0 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_badge_module_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='description',
            field=models.TextField(blank=True, help_text='Explain what the student accomplished to earn this badge.'),
        ),
    ]
