# Generated by Django 6.0.7 on 2026-08-01 09:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0004_module_has_lessons_alter_module_has_exams'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSCEExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('name', models.CharField(max_length=200)),
                ('retry_times', models.PositiveSmallIntegerField(default=0, help_text='Total number of attempts allowed for each student.')),
                ('mcq_timer', models.PositiveIntegerField(help_text='Time allowed for the MCQ section, in minutes.')),
                ('osce_station', models.CharField(choices=[('bp', 'BP'), ('ecg', 'Ecg'), ('none', 'None')], default='none', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osce_exams', to='modules.module')),
            ],
            options={
                'ordering': ('year', 'module__order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OSCEQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image_link', models.URLField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='osce.osceexam')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OSCEAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='osce.oscequestion')),
            ],
            options={
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='osceexam',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_osce_exam_name_per_module'),
        ),
    ]
