# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osceexam',
            name='diastolic_pressure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Diastolic blood pressure in mmHg.', null=True),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v1',
            field=models.BooleanField(default=False, verbose_name='V1'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v2',
            field=models.BooleanField(default=False, verbose_name='V2'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v3',
            field=models.BooleanField(default=False, verbose_name='V3'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v4',
            field=models.BooleanField(default=False, verbose_name='V4'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v5',
            field=models.BooleanField(default=False, verbose_name='V5'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='ecg_v6',
            field=models.BooleanField(default=False, verbose_name='V6'),
        ),
        migrations.AddField(
            model_name='osceexam',
            name='systolic_pressure',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Systolic blood pressure in mmHg.', null=True),
        ),
    ]
