# Generated by Django 6.0.7 on 2026-08-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osce', '0002_osceexam_station_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osceexam',
            name='mcq_timer',
            field=models.PositiveIntegerField(
                help_text='Time allowed for the MCQ section, in Seconds.'
            ),
        ),
    ]
