# Generated by Django 6.0.7 on 2026-08-02 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osce', '0003_alter_osceexam_mcq_timer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OSCEAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_passed', models.BooleanField(default=False)),
                ('practical_details', models.TextField(blank=True)),
                ('mcq_score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='osce.osceexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osce_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OSCEAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='osce.oscequestion')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_attempts', to='osce.osceanswer')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='osce.osceattempt')),
            ],
            options={
                'ordering': ('question__order', 'question__pk'),
            },
        ),
    ]
