# Generated by Django 6.0.7 on 2026-08-09

from django.db import migrations, models


def convert_seconds_to_minutes(apps, schema_editor):
    OSCEExam = apps.get_model('osce', 'OSCEExam')
    for exam in OSCEExam.objects.all().only('pk', 'mcq_timer'):
        # Round up so an existing timer never becomes shorter after conversion.
        exam.mcq_timer = (exam.mcq_timer + 59) // 60
        exam.save(update_fields=['mcq_timer'])


class Migration(migrations.Migration):
    dependencies = [('osce', '0004_osceattempt_osceanswerrecord')]

    operations = [
        migrations.RunPython(convert_seconds_to_minutes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='osceexam',
            name='mcq_timer',
            field=models.PositiveIntegerField(help_text='Time allowed for the MCQ section, in minutes.'),
        ),
    ]
