# Generated by Django 6.0.7 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('osce', '0005_mcq_timer_minutes')]

    operations = [
        migrations.AddField(model_name='osceattempt', name='practical_score', field=models.PositiveSmallIntegerField(default=0)),
        migrations.AddField(model_name='osceattempt', name='practical_total', field=models.PositiveSmallIntegerField(default=0)),
    ]
