# Generated by Django 6.0.7 on 2026-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osce', '0006_osceattempt_practical_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='osceexam',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Make this OSCE available to every authenticated student.'),
        ),
    ]
