# Generated by Django 6.0.7 on 2026-08-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_module_has_lessons_alter_module_has_exams'),
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_subcategories', to='modules.module')),
            ],
            options={
                'verbose_name': 'Text subcategory',
                'verbose_name_plural': 'Text subcategories',
                'ordering': ('module__year', 'module__order', 'order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='textcontent',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_contents', to='text.textsubcategory'),
        ),
        migrations.AddConstraint(
            model_name='textsubcategory',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_text_subcategory_name_per_module'),
        ),
    ]
