# Generated by Django 6.0.7 on 2026-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_textsubcategory_textcontent_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='is_trial',
            field=models.BooleanField(default=False, help_text='Make this text content available to every authenticated student.'),
        ),
    ]
